services:
  caddy:
    image: caddy:latest
    network_mode: host
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
    restart: unless-stopped

  visitors:
    image: trasa/elite-visitors:latest
    network_mode: host
    secrets:
      - redis-auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://127.0.0.1:8080
      - REDIS_AUTH_FILE=/run/secrets/redis-auth
      - ConnectionStrings__redis-Production=private-elite-visitors-redis-do-user-18343723-0.d.db.ondigitalocean.com:25061,abortConnect=false,ssl=true
    restart: unless-stopped

volumes:
    caddy_data:
    caddy_config:

secrets:
  redis-auth:
    file: /home/deploy/redis-auth-secret
