version: '3.8'

services:
  caddy:
    image: caddy:latest
    network_mode: host
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy_data:/data
        - caddy_config:/config
    restart: unless-stopped

  visitors:
    image: trasa/elite-visitors:latest
    network_mode: host
    ports:
      - target: 8080
        published: 8080
        mode: host
    secrets:
      - redis-auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - REDIS_AUTH_FILE=/run/secrets/redis-auth
      - ConnectionStrings__redis-Production=rediss://default:@private-elite-visitors-redis-do-user-18343723-0.d.db.ondigitalocean.com:25061
    restart: unless-stopped


volumes:
    caddy_data:
    caddy_config:

secrets:
  redis-auth:
    file: /home/deploy/redis-auth-secret
