services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile
        - caddy-data:/data
        - caddy-config:/config
    depends_on:
      - visitors

  visitors:
    image: trasa/elite-visitors:latest
    ports:
        - "8080:8080"
    secrets:
      - redis-auth
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - REDIS_AUTH_FILE=/run/secrets/redis-auth
      - ConnectionStrings__redis-Production=rediss://default@:private-elite-visitors-redis-do-user-18343723-0.d.db.ondigitalocean.com:25061
    extra_hosts:
      - "private-elite-visitors-redis-do-user-18343723-0.d.db.ondigitalocean.com:10.124.16.2"

volumes:
    caddy-data:
      driver: local
    caddy-config:
      driver: local

secrets:
  redis-auth:
    external: true
