name: Build and Push Images

on:
  workflow_dispatch:

jobs:
  build-push:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for nbgv versioning

      - name: build elite-visitors image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/elite-visitors:latest .

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_TOKEN }}

      - name: push elite-visitors
        run: docker push ${{ secrets.DOCKER_USERNAME }}/elite-visitors:latest
